# Generated by Django 3.0.8 on 2020-07-15 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Lecture',
        ),
    ]
