name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
      env:
        SECRET_KEY:  'SOME_SCRET_KEY'
        DEBUG:  true
    
    
    # Setup Python (faster than using Python container)
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install pipenv
      run: |
        python3 -m pip install --upgrade pipenv wheel
    
    - name: Display Python version
      run: python3 -v
    
    - name: Install dependecies
      run: |
        pipenv install -d
    
    - name: Run tests with pipenv and pytest
      run: |
        pipenv run pytest
    
    - name: Code best pratices style
      run: |
        pipenv run flake8
